rc4sxs-crypt.o: arc4_common.h
rc4sxs-crypt.o: config.h
rc4sxs-crypt.o: fragments/include/dim_sdbrke8ae851uitgzm4nv3ea2.h
rc4sxs-crypt.o: fragments/include/getopt_nh7lll77vb62ycgwzwf30zlln.h
rc4sxs-crypt.o: rc4sxs-crypt.c
treyfer-cfb-256.o: config.h
treyfer-cfb-256.o: treyfer-cfb-256.c
treyfer-cfb-256.o: treyfer_sbox.h
treyfer-ofb.o: fragments/include/dim_sdbrke8ae851uitgzm4nv3ea2.h
treyfer-ofb.o: treyfer-ofb.c
