.POSIX:
# v2020.322

TARGETS = rc4hash
DOCS = README.html

CFLAGS = -D NDEBUG -O
LDFLAGS = -s

PROJECT_CPPFLAGS = -I .
AUGMENTED_CPPFLAGS = $(CPPFLAGS) $(PROJECT_CPPFLAGS)
AUGMENTED_CFLAGS= $(AUGMENTED_CPPFLAGS) $(CFLAGS)

.PHONY: all clean doc

all: $(TARGETS)

doc: $(DOCS)

$(DOCS): $(DOCS:.html=.adoc)
	asciidoc $?

clean:
	-rm $(TARGETS) $(DOCS)

.c:
	$(CC) $(AUGMENTED_CFLAGS) $(LDFLAGS) -o $@ $<
