'rc4hash' - abuse ARCFOUR as a hash algorithm
=============================================
Guenther Brunthaler

'rc4hash' is a tool similar to 'sha256sum' but much simpler to
implement, while still being reasonably fast.

While 256 bit is the default, the size of the generated hash can
in fact be chosen freely. This allows the utility also to be used
for key stretching or key compaction. By combining this with a
salt, it can also be used as a password-based key derivation
function.

The main reason to use it is that the algorithm is easy to
remember and can thus be reimplemented from memory without access
to any written specification.

For instance, one might find oneself in a situation without any
external network access and no source code to a hash algorithm or
the specification to such. 'rc4hash' is still simple enough to be
implemented from memory, provided 'ARCFOUR' has also been
remembered.

The idea is to set the contents of the file to be hashed to be
hashed as the key for the 'ARCFOUR'-variant algorithm.

Then use the first 256 output bits of the 'ARCFOUR'-variant
pseudorandom stream as a message digest and output it, encoded as
a base-32 string using a custom alphabet.

The custom base-32 alphabet uses all ASCII upper-case letters and
decimal digits, excluding "0" (zero), "1" (one), "I" like India
and "O" like Oscar. Alternative supported digest output formats
are hexadecimal and binary raw bytes.

The 'ARCFOUR'-variant is a minimally modified 'ARCFOUR-drop3072'
algorithm: Its key setup processes all octets of the key exactly
once. No key octets are ignored or repeated cyclically.

'ARCFOUR-drop3072' is the original 'ARCFOUR' algorithm modified
in order to discard its first 3072 generated pseudorandom output
octets. This prevents some known attacks against the unmodified
algorithm.

While I a have serious doubts whether or not this hash algorithm
is cryptographically secure, it certainly is fast as hell.

When unsed inside of an encrypted message, i. e. MtE, then its
cryptographic shortcomings should not be too significant. It
would probably be a bad choice for EtM, though.

Use it in situations when you want a very fast hash output that
is much larger than that of cksum and much faster than md5sum.

The code footprint of the implementation is also very small,
because 'ARCFOUR' is a much simpler algorithm than any known
cryptographic hash algorithm.

One disadvantage of the algorithm is the large startup overhead
causing by dropping the initial portion of the output keystream.
It is therefore only efficient for larger files.

Since the beginning of this project, a couple of additional
utilties have been added as well:

* 'rc4dropN' - Implements the original 'ARCFOUR' algorithm as
  well as its 'ARCFOUR-dropN' variants, such as 'ARCFOUR-drop768'
  and 'ARCFOUR-drop3072'.

* 'treyfer-ofb' - Implements the 'treyfer' block cipher in OFB
  mode, making it into a stream cipher. The cipher has been
  chosen because of its extreme simplicity, similar in complexity
  to 'ARCFOUR'. The cipher itself is weak, but combining it with
  'rc4dropN' will drastically reduce the probability that known
  weaknesses in 'ARCFOUR' can be exploited. Unfortunately,
  'treyfer' is about 8 times slower than 'ARCFOUR'.

* 'sxs-crypt' - Encrypts or decrypts three one-time-pads with
  standard input in a simple 'SUBTRACT-XOR-SUBTRACT' scheme. The
  one-time-pads usually come from a pipe and are provided by
  CSPRNGs. 'rc4dropN' and 'treyfer-ofb' can both be used as
  CSPRNGs by encrypting '/dev/zero'. 'sxs-crypt' eliminates the
  immediate threat of bit flipping attacks otherwise possible
  with any one-time pad encryption.
