rc4dropN: rc4dropN.o $(LIBS)
	$(CC) $(LDFLAGS) -o $@ rc4dropN.o $(LIBS)
rc4hash: rc4hash.o $(LIBS)
	$(CC) $(LDFLAGS) -o $@ rc4hash.o $(LIBS)
sxs-crypt: sxs-crypt.o $(LIBS)
	$(CC) $(LDFLAGS) -o $@ sxs-crypt.o $(LIBS)
treyfer-ofb: treyfer-ofb.o $(LIBS)
	$(CC) $(LDFLAGS) -o $@ treyfer-ofb.o $(LIBS)
