getopt_simplest.o: getopt_simplest.c
getopt_simplest.o: include/getopt_nh7lll77vb62ycgwzwf30zlln.h
getopt_simplest_mand_arg.o: getopt_simplest_mand_arg.c
getopt_simplest_mand_arg.o: include/getopt_nh7lll77vb62ycgwzwf30zlln.h
getopt_simplest_perror_missing_arg.o: getopt_simplest_perror_missing_arg.c
getopt_simplest_perror_missing_arg.o: include/getopt_nh7lll77vb62ycgwzwf30zlln.h
getopt_simplest_perror_opt.o: getopt_simplest_perror_opt.c
getopt_simplest_perror_opt.o: include/getopt_nh7lll77vb62ycgwzwf30zlln.h
